import type { ComponentType as ReactComponentType } from 'react';
import {
  Container,
  Card,
  Tabs,
  Modal,
  Accordion,
  Divider,
  Form,
  TextInput,
  TextArea,
  NumberInput,
  EmailInput,
  PasswordInput,
  Dropdown,
  Checkbox,
  Radio,
  DatePicker,
  TimePicker,
  Upload,
  Text,
  MarkdownDisplay,
  ImageDisplay,
  Badge,
  ListDisplay,
  Progress,
  Button,
  TableDisplay,
  DynamicChart,
} from '../components/ui';

export const componentRegistry: Record<string, ReactComponentType<any>> = {
  container: Container,
  form: Form,
  card: Card,
  button: Button,
  text: Text,
  markdown: MarkdownDisplay,
  input: TextInput,
  textarea: TextArea,
  number_input: NumberInput,
  email_input: EmailInput,
  password_input: PasswordInput,
  dropdown: Dropdown,
  checkbox: Checkbox,
  radio: Radio,
  date_picker: DatePicker,
  time_picker: TimePicker,
  table: TableDisplay,
  chart: DynamicChart,
  upload: Upload,
  image: ImageDisplay,
  tabs: Tabs,
  modal: Modal,
  divider: Divider,
  badge: Badge,
  list: ListDisplay,
  progress: Progress,
  accordion: Accordion,
};
