"""
Nexora AI — Event and Upload API Endpoints.

Handles event signals emitted from dynamic frontend components (e.g. form submit)
and processes binary/text file uploads.
"""

from __future__ import annotations

import logging
import os
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, UploadFile, status, File
from app.agents.orchestrator import Orchestrator
from app.api.dependencies import get_orchestrator
from app.core.config import get_settings, Settings
from app.schemas.ui_schema import EventRequest, EventResponse

logger = logging.getLogger(__name__)
settings = get_settings()

router = APIRouter(tags=["Events"])


@router.post(
    "/event",
    response_model=EventResponse,
    status_code=status.HTTP_200_OK,
    summary="Submit an event generated by dynamic UI components",
)
async def post_event(
    request: EventRequest,
    orchestrator: Orchestrator = Depends(get_orchestrator),
) -> EventResponse:
    """Submit a component event back to the AI orchestrator.

    When the user submits a dynamically generated form or clicks an action
    button, the frontend fires this endpoint. The agent intercepts it as
    an implicit event turn and continues its reasoning sequence.

    Args:
        request: The event details (type, payload).
        orchestrator: Injected orchestrator brain.

    Returns:
        EventResponse containing the next step's state and dynamic UI.
    """
    try:
        response = await orchestrator.handle_event(
            session_id=request.session_id,
            event_type=request.event_type,
            payload=request.payload,
        )
        return response
    except ValueError as exc:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=str(exc),
        )
    except Exception as exc:
        logger.exception("Error in post_event API")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred during event processing: {exc}",
        )


@router.post(
    "/upload",
    status_code=status.HTTP_201_CREATED,
    summary="Upload files associated with a session",
)
async def post_upload(
    session_id: str,
    file: UploadFile = File(...),
) -> dict[str, Any]:
    """Upload a file to the workspace.

    The file will be saved in the uploads directory and its metadata
    returned so the AI agent can incorporate it into subsequent steps.

    Args:
        session_id: Active session UUID.
        file: Binary upload payload.

    Returns:
        A dict containing file_name, file_path, and sizeBytes.
    """
    try:
        # Resolve uploads directory inside workspace config
        upload_dir = settings.UPLOAD_DIR
        os.makedirs(upload_dir, exist_ok=True)

        # Create session-specific folder to prevent name collisions
        session_dir = os.path.join(upload_dir, session_id)
        os.makedirs(session_dir, exist_ok=True)

        file_path = os.path.join(session_dir, file.filename)

        # Save to disk
        contents = await file.read()
        with open(file_path, "wb") as f:
            f.write(contents)

        logger.info(
            "File uploaded successfully — name: %s  session: %s  path: %s",
            file.filename,
            session_id,
            file_path,
        )

        return {
            "filename": file.filename,
            "path": f"/uploads/{session_id}/{file.filename}",
            "size": len(contents),
            "content_type": file.content_type,
        }

    except Exception as exc:
        logger.exception("Error in post_upload API")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to upload file: {exc}",
        )
